[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
whistl = "9xe1gCVh7kNqjfRbidVUpWBcS2A4EstvkBMkxc34LWRR"

[programs.devnet]
whistl = "9xe1gCVh7kNqjfRbidVUpWBcS2A4EstvkBMkxc34LWRR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 180000

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
